version: '2'

services:
    reverseproxy:
        image: sogis/nginx-reverseproxy:0.0.3
        ports:
            - 8080:8080
            - 8081:8081
            - 8082:8082
            - 80:80
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always

    avgbs2mtab:
        depends_on:
            - reverseproxy
        image: sogis/avgbs2mtab-web-service:latest
        restart: always            

    ilivalidator:
        depends_on:
            - reverseproxy
        image: sogis/ilivalidator-web-service:latest
        restart: always        