version: '2'

services:
    reverseproxy:
        image: sogis/nginx-reverseproxy:0.0.3
        ports:
            - 80:80
        restart: always

    avgbs2mtab:
        depends_on:
            - reverseproxy
        image: sogis/avgbs2mtab-web-service:latest
        restart: always            

    ilivalidator:
        depends_on:
            - reverseproxy
        image: sogis/ilivalidator-web-service:latest
        restart: always        